### ISSUE TITLE
Add support for 'invert' and 'exclude'

### ISSUE THREAD

**Issue by samsharp99** [flyrmyr/system-flow-card#2]
Currently the numbers do not add up as all of the 'consumption' items show as providing _into_ the card - please add support for the 'invert?' property so that the flow direction is shown correctly.

![image](https://user-images.githubusercontent.com/7469882/215325300-20a9ec00-7a57-4e62-9347-c0ee518e9f3b.png)

I would also like the 'exclude' to be supported so I can add fuel/gas information to the card without it adding to the consumption total.

**Comment by flyrmyr** [comment]
<img width="425" alt="Screenshot 2023-02-07 at 3 35 33 PM" src="https://user-images.githubusercontent.com/14035884/217382198-b8b8b26f-77b8-46a6-9095-3a252d2be10e.png">

Hmm, so the `invert` and `exclude` properties have been available and working for a while for me... Could you try to grab the latest dist.js file and overwrite the one you're using?

**Comment by flyrmyr** [comment]
The latest v0.1.0 release includes these requests.
